name: flight-route-project

services:
  flight-route-db:
    image: mysql:latest
    container_name: flight-route-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HZk9vdm7qVPL3A6
      MYSQL_DATABASE: flight_route
      MYSQL_USER: phoenixsqluser
      MYSQL_PASSWORD: phoenixsqluser
    volumes:
      - ~/flight-route-data:/var/lib/mysql
    ports:
      - "33055:3306"
    networks:
      - default

networks:
  default:
    name: flight-route-project-network